/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ProjectController;
import javax.swing.JOptionPane;
import model.Project;

/**
 *
 * @author PC
 */
public class ProjectDialogScreen extends javax.swing.JDialog {

    ProjectController controller;
    
    
    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new ProjectController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToolBarAddProject = new javax.swing.JPanel();
        jLabelToolBarAddProjectTitle = new javax.swing.JLabel();
        jLabelToolBarAddProjectIcon = new javax.swing.JLabel();
        jPanelAddProject = new javax.swing.JPanel();
        jLabelAddProjectNameTitle = new javax.swing.JLabel();
        jTextFieldAddProjectName = new javax.swing.JTextField();
        jLabelAddProjectDescTitle = new javax.swing.JLabel();
        jScrollPane1AddProjectDesc = new javax.swing.JScrollPane();
        jTextAreaAddProjectDesc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelToolBarAddProject.setBackground(new java.awt.Color(0, 153, 102));

        jLabelToolBarAddProjectTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelToolBarAddProjectTitle.setForeground(java.awt.Color.white);
        jLabelToolBarAddProjectTitle.setText(" Projeto");

        jLabelToolBarAddProjectIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelToolBarAddProjectIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check-mark-12-32.png"))); // NOI18N
        jLabelToolBarAddProjectIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelToolBarAddProjectIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolBarAddProjectLayout = new javax.swing.GroupLayout(jPanelToolBarAddProject);
        jPanelToolBarAddProject.setLayout(jPanelToolBarAddProjectLayout);
        jPanelToolBarAddProjectLayout.setHorizontalGroup(
            jPanelToolBarAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarAddProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelToolBarAddProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelToolBarAddProjectIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelToolBarAddProjectLayout.setVerticalGroup(
            jPanelToolBarAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelToolBarAddProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelToolBarAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelToolBarAddProjectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelToolBarAddProjectIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelAddProject.setBackground(java.awt.Color.white);

        jLabelAddProjectNameTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddProjectNameTitle.setText("Nome");

        jTextFieldAddProjectName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelAddProjectDescTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddProjectDescTitle.setText("Descrição");

        jTextAreaAddProjectDesc.setColumns(20);
        jTextAreaAddProjectDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaAddProjectDesc.setRows(5);
        jScrollPane1AddProjectDesc.setViewportView(jTextAreaAddProjectDesc);

        javax.swing.GroupLayout jPanelAddProjectLayout = new javax.swing.GroupLayout(jPanelAddProject);
        jPanelAddProject.setLayout(jPanelAddProjectLayout);
        jPanelAddProjectLayout.setHorizontalGroup(
            jPanelAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1AddProjectDesc)
                    .addComponent(jLabelAddProjectNameTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAddProjectName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddProjectDescTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAddProjectLayout.setVerticalGroup(
            jPanelAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAddProjectNameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAddProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelAddProjectDescTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1AddProjectDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolBarAddProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolBarAddProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAddProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelToolBarAddProjectIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelToolBarAddProjectIconMouseClicked
        
        try{
            if(!jTextFieldAddProjectName.getText().equals("")){
                Project project = new Project();
                project.setName(jTextFieldAddProjectName.getText());
                project.setDescription(jTextAreaAddProjectDesc.getText());
                controller.save(project);
                JOptionPane.showMessageDialog(rootPane, "Projeto salvo com sucesso!");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane, "O projeto não foi salvo pois o campo nome ficou vazio...");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
    }//GEN-LAST:event_jLabelToolBarAddProjectIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAddProjectDescTitle;
    private javax.swing.JLabel jLabelAddProjectNameTitle;
    private javax.swing.JLabel jLabelToolBarAddProjectIcon;
    private javax.swing.JLabel jLabelToolBarAddProjectTitle;
    private javax.swing.JPanel jPanelAddProject;
    private javax.swing.JPanel jPanelToolBarAddProject;
    private javax.swing.JScrollPane jScrollPane1AddProjectDesc;
    private javax.swing.JTextArea jTextAreaAddProjectDesc;
    private javax.swing.JTextField jTextFieldAddProjectName;
    // End of variables declaration//GEN-END:variables
}
