
package view;

import controller.TaskController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;


public class TaskDialogScreen extends javax.swing.JDialog {

    TaskController controller;
    Project project;
  
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        hideErrorFields();
        controller = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanelToolBarAddTask = new javax.swing.JPanel();
        jPanelToolBarAddTaskTitle = new javax.swing.JLabel();
        jPanelToolBarAddTaskIcon = new javax.swing.JLabel();
        jPanelAddTask = new javax.swing.JPanel();
        jPanelAddTaskBackground = new javax.swing.JPanel();
        jLabelAddTaskNameTitle = new javax.swing.JLabel();
        jTextFieldAddTaskName = new javax.swing.JTextField();
        jLabelAddTaskDescTitle = new javax.swing.JLabel();
        jScrollPaneAddTaskDesc = new javax.swing.JScrollPane();
        jTextAreaAddTaskDesc = new javax.swing.JTextArea();
        jLabelAddTaskDeadlineTitle = new javax.swing.JLabel();
        jLabelAddTaskNotesTitle = new javax.swing.JLabel();
        jScrollPaneAddTaskNotes = new javax.swing.JScrollPane();
        jTextAreaAddTaskNotes = new javax.swing.JTextArea();
        jFormattedTextFieldAddTaskDeadline = new javax.swing.JFormattedTextField();
        jLabelNameError = new javax.swing.JLabel();
        jLabelDeadlineError = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelToolBarAddTask.setBackground(new java.awt.Color(0, 153, 102));

        jPanelToolBarAddTaskTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanelToolBarAddTaskTitle.setForeground(java.awt.Color.white);
        jPanelToolBarAddTaskTitle.setText(" Tarefa");

        jPanelToolBarAddTaskIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelToolBarAddTaskIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check-mark-12-32.png"))); // NOI18N
        jPanelToolBarAddTaskIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelToolBarAddTaskIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolBarAddTaskLayout = new javax.swing.GroupLayout(jPanelToolBarAddTask);
        jPanelToolBarAddTask.setLayout(jPanelToolBarAddTaskLayout);
        jPanelToolBarAddTaskLayout.setHorizontalGroup(
            jPanelToolBarAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarAddTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelToolBarAddTaskTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelToolBarAddTaskIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelToolBarAddTaskLayout.setVerticalGroup(
            jPanelToolBarAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelToolBarAddTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelToolBarAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelToolBarAddTaskTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelToolBarAddTaskIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelAddTaskBackground.setBackground(java.awt.Color.white);

        jLabelAddTaskNameTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddTaskNameTitle.setText("Nome");

        jLabelAddTaskDescTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddTaskDescTitle.setText("Descrição");

        jTextAreaAddTaskDesc.setColumns(20);
        jTextAreaAddTaskDesc.setRows(5);
        jScrollPaneAddTaskDesc.setViewportView(jTextAreaAddTaskDesc);

        jLabelAddTaskDeadlineTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddTaskDeadlineTitle.setText("Prazo");

        jLabelAddTaskNotesTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAddTaskNotesTitle.setText("Notas");

        jTextAreaAddTaskNotes.setColumns(20);
        jTextAreaAddTaskNotes.setRows(5);
        jScrollPaneAddTaskNotes.setViewportView(jTextAreaAddTaskNotes);

        jFormattedTextFieldAddTaskDeadline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabelNameError.setForeground(new java.awt.Color(255, 51, 51));
        jLabelNameError.setText("o campo nome é obrigatorio");

        jLabelDeadlineError.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDeadlineError.setText("o campo prazo é obrigatorio");

        javax.swing.GroupLayout jPanelAddTaskBackgroundLayout = new javax.swing.GroupLayout(jPanelAddTaskBackground);
        jPanelAddTaskBackground.setLayout(jPanelAddTaskBackgroundLayout);
        jPanelAddTaskBackgroundLayout.setHorizontalGroup(
            jPanelAddTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddTaskBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAddTaskDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jLabelAddTaskNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAddTaskName)
                    .addComponent(jLabelAddTaskDescTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAddTaskDeadlineTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAddTaskNotesTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneAddTaskNotes)
                    .addComponent(jFormattedTextFieldAddTaskDeadline)
                    .addComponent(jLabelNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDeadlineError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelAddTaskBackgroundLayout.setVerticalGroup(
            jPanelAddTaskBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddTaskBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAddTaskNameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAddTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabelNameError)
                .addGap(18, 18, 18)
                .addComponent(jLabelAddTaskDescTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneAddTaskDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabelAddTaskDeadlineTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldAddTaskDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDeadlineError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabelAddTaskNotesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneAddTaskNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelAddTaskLayout = new javax.swing.GroupLayout(jPanelAddTask);
        jPanelAddTask.setLayout(jPanelAddTaskLayout);
        jPanelAddTaskLayout.setHorizontalGroup(
            jPanelAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddTaskBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAddTaskLayout.setVerticalGroup(
            jPanelAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAddTaskBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolBarAddTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAddTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolBarAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAddTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelToolBarAddTaskIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelToolBarAddTaskIconMouseClicked
        
        try{
            if(isFieldsValids()){
                Task task = new Task();
                task.setIdProject(project.getId());
                task.setName(jTextFieldAddTaskName.getText());
                task.setDescription(jTextAreaAddTaskDesc.getText());
                task.setNotes(jTextAreaAddTaskNotes.getText());
                task.setIsCompleted(false);

                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date deadline = null;
                deadline = dateFormat.parse(jFormattedTextFieldAddTaskDeadline.getText());
                task.setDeadline(deadline);

                controller.save(task);
                JOptionPane.showMessageDialog(rootPane, "Tarefa salva com sucesso!");
                this.dispose();
            }else{
                hideErrorFields();
                if(jTextFieldAddTaskName.getText().isEmpty()){
                    jLabelNameError.setVisible(true);
                }
                if(jFormattedTextFieldAddTaskDeadline.getText().isEmpty()){
                    jLabelDeadlineError.setVisible(true);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jPanelToolBarAddTaskIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldAddTaskDeadline;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAddTaskDeadlineTitle;
    private javax.swing.JLabel jLabelAddTaskDescTitle;
    private javax.swing.JLabel jLabelAddTaskNameTitle;
    private javax.swing.JLabel jLabelAddTaskNotesTitle;
    private javax.swing.JLabel jLabelDeadlineError;
    private javax.swing.JLabel jLabelNameError;
    private javax.swing.JPanel jPanelAddTask;
    private javax.swing.JPanel jPanelAddTaskBackground;
    private javax.swing.JPanel jPanelToolBarAddTask;
    private javax.swing.JLabel jPanelToolBarAddTaskIcon;
    private javax.swing.JLabel jPanelToolBarAddTaskTitle;
    private javax.swing.JScrollPane jScrollPaneAddTaskDesc;
    private javax.swing.JScrollPane jScrollPaneAddTaskNotes;
    private javax.swing.JTextArea jTextAreaAddTaskDesc;
    private javax.swing.JTextArea jTextAreaAddTaskNotes;
    private javax.swing.JTextField jTextFieldAddTaskName;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project){
        this.project = project;
    }
    
    public void hideErrorFields(){
        jLabelNameError.setVisible(false);
        jLabelDeadlineError.setVisible(false);
    }
    
    public boolean isFieldsValids(){
        if((!jTextFieldAddTaskName.getText().isEmpty()) && (!jFormattedTextFieldAddTaskDeadline.getText().isEmpty())){
            return true;
        }else
            return false;
    }
}
